import { createSlice } from '@reduxjs/toolkit'

// Define a Redux slice named 'previewModal' with initial state
const previewModal = createSlice({
  name: 'previewModal', // The name of the slice
  initialState: {
    data: {}, // Initial data object
    isOpen: false // Initial state for the modal's open status
  },
  reducers: {
    // Reducer function to set the preview details and open status
    setPreviewDetails: (state, action) => {
      const { data, isOpen } = action.payload
      state.data = data // Update the data
      state.isOpen = isOpen // Update the open status
    },
    // Reducer function to toggle the modal's open status
    updateOpenStatus: (state) => {
      state.isOpen = !state.isOpen // Toggle the open status
    }
  }
})

// Action creators are generated for each case reducer function
export const { setPreviewDetails, updateOpenStatus } = previewModal.actions

// Export the reducer function generated by createSlice
export const previewModalSlice = previewModal.reducer
